# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tnr < Formula
  desc "Thunder Compute CLI"
  homepage "https://github.com/Thunder-Compute/thunder-cli"
  version "2.0.4"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Thunder-Compute/thunder-cli/releases/download/v2.0.4/tnr_2.0.4_darwin_amd64.tar.gz"
    sha256 "d2596e68c5a4a116bb439ee8c8972373c850efc3f72a740206f276aa949fd46a"

    def install
      bin.install "tnr"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Thunder-Compute/thunder-cli/releases/download/v2.0.4/tnr_2.0.4_darwin_arm64.tar.gz"
    sha256 "e969dfd2dcfa53ceb669a76d25f04188a1b79f5e357a84b316a43fea976346cc"

    def install
      bin.install "tnr"
    end
  end

  test do
    system "#{bin}/tnr", "--version"
  end
end
