# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Tnr < Formula
  desc "Thunder Compute CLI"
  homepage "https://github.com/Thunder-Compute/thunder-cli"
  version "0.0.34"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/Thunder-Compute/thunder-cli/releases/download/v0.0.34/tnr_0.0.34_darwin_amd64.tar.gz"
    sha256 "02283cc25e492844c2e8c3d9f93890ec2706d6e17b370bb8ca409963e15649d3"

    def install
      bin.install "tnr"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/Thunder-Compute/thunder-cli/releases/download/v0.0.34/tnr_0.0.34_darwin_arm64.tar.gz"
    sha256 "086a9c96f1924dce3d0c49f0fadec29e3b81efc6af207e9f6e615c2de62ebb99"

    def install
      bin.install "tnr"
    end
  end

  test do
    system "#{bin}/tnr", "--version"
  end
end
